### PR TITLE
Token section

### LINKED ISSUE #72: Implement Token section
### Context

We need a new section showing user token data. Data should include the number of tokens and the list of vests if available.

The section should also show Claim action when vested tokens are available. We need some notification mechanism to ping users when vesting is over.

Design TBD

### PR DESCRIPTION
**Pull request by viganzeqiri**
Closes #72

### CODE REVIEW

**Comment by xn3cr0nx** [comment]
Hey Vigan, pasting the screenshot here, I was testing it out in preview, and this is what I see. I think we are missing PDN in the labels because without it, it really seems out of context and it is not clear what the windows refer to. Also, I think the burn should be disabled if the balance is less than the burn ratio.

Not sure why, but in preview it requires mainnet, if I switch to goerli it shows wrong network, although I set the NEXT_PUBLIC_CHAIN env var for preview environment to 0x5.

image

**Comment by viganzeqiri** [comment]
> Hey Vigan, pasting the screenshot here, I was testing it out in preview, and this is what I see. I think we are missing PDN in the labels because without it, it really seems out of context and it is not clear what the windows refer to. Also, I think the burn should be disabled if the balance is less than the burn ratio.
> 
> Not sure why, but in preview it requires mainnet, if I switch to goerli it shows wrong network, although I set the NEXT_PUBLIC_CHAIN env var for preview environment to 0x5.
> 
> image

I think the key is wrong, try this `NEXT_PUBLIC_CHAIN_ID`

**Comment by xn3cr0nx** [comment]
> > Hey Vigan, pasting the screenshot here, I was testing it out in preview, and this is what I see. I think we are missing PDN in the labels because without it, it really seems out of context and it is not clear what the windows refer to. Also, I think the burn should be disabled if the balance is less than the burn ratio.
> > Not sure why, but in preview it requires mainnet, if I switch to goerli it shows wrong network, although I set the NEXT_PUBLIC_CHAIN env var for preview environment to 0x5.
> > image
> 
> I think the key is wrong, try this `NEXT_PUBLIC_CHAIN_ID`.
> 
> The PDN symbol is fetched from the smart contract thats why its missing because the key you passed is wrong one

Confirmed, CHAIN_IN was set to the wrong network (mainnet), after the change this is the new output:

image

not sure if this messages in console are expected:

image

**Review by xn3cr0nx — APPROVED** [review]
LGTM

**Pull request merged**
